name: /scratch1/hyeonhoo/miniconda3/envs/my_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - expat=2.7.1
  - glew=2.1.0
  - icu=73.1
  - ld_impl_linux-64=2.44
  - libdrm=2.4.124
  - libegl=1.7.0
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgl=1.7.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libpciaccess=0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - patchelf=0.17.2
  - pkg-config=0.29.2
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wayland=1.24.0
  - wheel=0.45.1
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.11.0
      - antlr4-python3-runtime==4.9.3
      - beautifulsoup4==4.14.2
      - bokeh==3.8.1
      - cffi==2.0.0
      - clam==0.0.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - cython==0.29.37
      - d4rl==1.1
      - dm-control==1.0.34
      - dm-env==1.6
      - dm-reverb==0.14.0
      - dm-tree==0.1.9
      - einx==0.3.0
      - farama-notifications==0.0.4
      - fasteners==0.20
      - fonttools==4.60.1
      - frozendict==2.4.6
      - gdown==5.2.0
      - glfw==2.10.0
      - gym==0.23.1
      - gym-notices==0.1.0
      - gymnasium==0.29.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface==0.0.1
      - huggingface-hub==1.1.7
      - hydra-core==1.3.2
      - imageio==2.37.0
      - jaxtyping==0.3.3
      - keras==2.15.0
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - labmaze==1.0.6
      - loguru==0.7.3
      - lxml==6.0.2
      - matplotlib==3.10.7
      - metaworld==0.1.0
      - ml-dtypes==0.3.2
      - moviepy==2.2.1
      - mujoco==3.3.7
      - mujoco-py==2.1.2.14
      - narwhals==2.14.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - pillow==11.3.0
      - pip==25.3
      - plotly==6.5.0
      - portpicker==1.6.0
      - proglog==0.1.12
      - protobuf==3.20.3
      - pybullet==3.2.6
      - pycparser==2.23
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - python-dotenv==1.2.1
      - r3m==0.0.0
      - rdkit==2025.9.3
      - rlds==0.1.8
      - safetensors==0.6.2
      - shellingham==1.5.4
      - shimmy==0.2.1
      - soundfile==0.13.1
      - soupsieve==2.8
      - sympy==1.13.1
      - tensorboard==2.15.2
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - torch==2.5.1+cu121
      - torchsummary==1.5.1
      - torchtyping==0.1.5
      - torchvision==0.20.1
      - tornado==6.5.4
      - triton==3.1.0
      - typeguard==2.13.3
      - typer-slim==0.20.0
      - vector-quantize-pytorch==1.24.1
      - wadler-lindig==0.1.7
      - wrapt==1.14.2
      - xyzservices==2025.11.0
prefix: /scratch1/hyeonhoo/miniconda3/envs/my_env
